### PR TITLE
Fix Buying Bug

### LINKED ISSUE #110: Cannot Buy Pokemon With a Single Type
## Expected Behavior

The user should be able to buy a Pokemon with a single type and it should update the correct badge progress. 

## Actual/Current Behavior

When a user tries to buy a Pokemon with a single type, the app crashes. 

## Steps to Reproduce the Problem

  1. Buy a Pokemon with a single type

### PR DESCRIPTION
**Pull request by krferrell**
## Changes
1. Fixed an issue that prevented the user from buying a pokemon with one type without the app crashing

## Purpose
To prevent the app from crashing

## Approach
Declared local variables for the types and wrote an if statement to set the type2 only if it existed.

Closes #110

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
nice and easy fix

**Review by BlackCubes — APPROVED** [review]
Looks good, and I like the comments!

**Review by Gjhnsn — APPROVED** [review]
This badge system looks really cool. Good job!

**Review by connielion — APPROVED** [review]
Nice! Great job on redux too!

**Pull request merged**
