### PR TITLE
fix(gamepage):resize the slot container on laptop screens

### LINKED ISSUE #207: Gamepage media query
## Expected Behavior

Card grid shows at least first row of cards in gamepage

## Actual/Current Behavior

Card grid is cutoff in laptop sizes

## Steps to Reproduce the Problem

  1. Open game page and win a pokemon

### PR DESCRIPTION
**Pull request by gonzalespaulb**
## Changes
_List Changes Introduced by this PR_
1. Added a media query for laptop size

## Purpose
Better screen responsiveness

## Approach
SCSS Media Query

Closes #207

### CODE REVIEW

**Review by BlackCubes — APPROVED** [review]
Very nice change! Can't wait to see it :O

**Review by connielion — APPROVED** [review]
Niiiice.

**Review by Lap343 — APPROVED** [review]
Very nice for 1440p monitors

**Review by dannysanchez559 — APPROVED** [review]
first time seeing grid in the apprenticeship!

**Pull request merged**
