### PR TITLE
update version to 1.0.1

### LINKED ISSUE #176: V1.0.1 Patch
## V 1.0.1
- [x] #177
- [x]  #178
- [x]  #179 
- [x] #180 
- [x] #181 
- [x] #182 
- [x] #183 
- [x] #184
- [x] #192 
- [x] #193 
- [x] #196 
- [x] #201
- [x] #204 
- [x] #209
- [x] #207

### PR DESCRIPTION
**Pull request by JayDampitan**
## Changes
1. Update version

Closes #176

### CODE REVIEW

**Review by krferrell — APPROVED** [review]
Nailed it.

**Review by Gjhnsn — APPROVED** [review]
nice!

**Review by Lap343 — APPROVED** [review]
Wooooo!!!

**Review by JorgeLVilla — APPROVED** [review]
Can't wait to see it!

**Comment by dannysanchez559** [comment]
show that version number who's boss!

**Review by dannysanchez559 — COMMENTED** [review]
show that version number whos boss!

**Pull request merged**
