### PR TITLE
more information button background color

### LINKED ISSUE #180: More information button background color
Change more information button background color to improve contrast.

### PR DESCRIPTION
**Pull request by gonzalespaulb**
## Changes
_List Changes Introduced by this PR_
1. Button background color

## Purpose
Give more contrast to the button

## Approach
SCSS

Closes #180

### CODE REVIEW

**Review by krferrell — APPROVED** [review]
Nice color changes.

**Review by BlackCubes — APPROVED** [review]
Noice! Like ready _War and Peace_ by Tolstoy

**Review by Lap343 — APPROVED** [review]
Very nice CSS fixes

**Review by JorgeLVilla — APPROVED** [review]
Noice and clean.

**Pull request merged**
