### PR TITLE
fix the spacing issue when the percent is at 100

### LINKED ISSUE #181: Badge percent overflow
## Expected Behavior

Badge percentage should stay within its container and retain padding

## Actual/Current Behavior

Once the badge percentage hits 100% it touches the end of its container. 

## Steps to Reproduce the Problem

  1.  Buy squirtle, charmander, and bulbasaur to complete a badge.

### PR DESCRIPTION
**Pull request by gonzalespaulb**
## Changes
_List Changes Introduced by this PR_
1. Padding right on the percent container

## Purpose
Prevent the percent container from touching the parent when it is at 100%

## Approach
CSS

Closes #181

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
Simple fix. Good job just don't forget to pull from development before merging

**Review by BlackCubes — APPROVED** [review]
Very extensive, indeed. Good job!

**Review by JorgeLVilla — APPROVED** [review]
Nioiiceeee

**Review by krferrell — APPROVED** [review]
Looks good. There is also the short hand of padding: top right bottom left

**Comment by gonzalespaulb** [comment]
> Simple fix. Good job just don't forget to pull from development before merging

Good catch! Thanks

**Pull request merged**
